"""'ActualizacionAdmin'

Revision ID: 0e8c526c8322
Revises: 4b5cd9f80977
Create Date: 2025-07-30 19:43:41.264484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e8c526c8322'
down_revision: Union[str, None] = '4b5cd9f80977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrador', 'correo',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('administrador', 'contraseña',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrador', 'contraseña',
               existing_type=sa.VARCHAR(length=15),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('administrador', 'correo',
               existing_type=sa.VARCHAR(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
