"""'Cifradodecontraseñas'

Revision ID: 1ad0dacf223b
Revises: 5840280ce246
Create Date: 2025-07-18 12:57:04.531617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ad0dacf223b'
down_revision: Union[str, None] = '5840280ce246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['id_turista'])
    op.alter_column('turista', 'correo',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index('direccion', table_name='turista')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('direccion', 'turista', ['direccion'], unique=True)
    op.alter_column('turista', 'correo',
               existing_type=sa.VARCHAR(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
