"""'Actualizacion'

Revision ID: 33f5b6a551f7
Revises: a0c0bb44cf2f
Create Date: 2025-07-13 13:42:24.081318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33f5b6a551f7'
down_revision: Union[str, None] = 'a0c0bb44cf2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'horario',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('plan', 'ubicacion')
    op.add_column('reserva', sa.Column('numero_personas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'numero_personas')
    op.add_column('plan', sa.Column('ubicacion', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('plan', 'horario',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
