"""cambios2

Revision ID: 4b5cd9f80977
Revises: e86d465cd4be
Create Date: 2025-07-18 19:17:19.959729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b5cd9f80977'
down_revision: Union[str, None] = 'e86d465cd4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('contrasena', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('turista', 'contraseña')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('contraseña', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('turista', 'contrasena')
    # ### end Alembic commands ###
