"""'unicidad'

Revision ID: 4e2bc00203cf
Revises: da74fe659509
Create Date: 2025-07-14 22:35:29.698355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2bc00203cf'
down_revision: Union[str, None] = 'da74fe659509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'administrador', ['celular'])
    op.create_unique_constraint(None, 'administrador', ['contraseña'])
    op.create_unique_constraint(None, 'administrador', ['correo'])
    op.create_unique_constraint(None, 'administrador', ['identificacion'])
    op.create_unique_constraint(None, 'turista', ['contraseña'])
    op.create_unique_constraint(None, 'turista', ['celular'])
    op.create_unique_constraint(None, 'turista', ['correo'])
    op.create_unique_constraint(None, 'turista', ['direccion'])
    op.create_unique_constraint(None, 'turista', ['identificacion'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turista', type_='unique')
    op.drop_constraint(None, 'turista', type_='unique')
    op.drop_constraint(None, 'turista', type_='unique')
    op.drop_constraint(None, 'turista', type_='unique')
    op.drop_constraint(None, 'turista', type_='unique')
    op.drop_constraint(None, 'administrador', type_='unique')
    op.drop_constraint(None, 'administrador', type_='unique')
    op.drop_constraint(None, 'administrador', type_='unique')
    op.drop_constraint(None, 'administrador', type_='unique')
    # ### end Alembic commands ###
