"""'unicidad2'

Revision ID: 5840280ce246
Revises: 4e2bc00203cf
Create Date: 2025-07-15 23:42:04.016950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5840280ce246'
down_revision: Union[str, None] = '4e2bc00203cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hotel', ['direccion'])
    op.create_unique_constraint(None, 'informe', ['nombre'])
    op.create_unique_constraint(None, 'plan', ['descripcion'])
    op.create_unique_constraint(None, 'plan', ['nombre'])
    op.create_unique_constraint(None, 'ubicacion', ['direccion'])
    op.create_unique_constraint(None, 'ubicacion', ['latitud'])
    op.create_unique_constraint(None, 'ubicacion', ['longitud'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ubicacion', type_='unique')
    op.drop_constraint(None, 'ubicacion', type_='unique')
    op.drop_constraint(None, 'ubicacion', type_='unique')
    op.drop_constraint(None, 'plan', type_='unique')
    op.drop_constraint(None, 'plan', type_='unique')
    op.drop_constraint(None, 'informe', type_='unique')
    op.drop_constraint(None, 'hotel', type_='unique')
    # ### end Alembic commands ###
