"""'Cifradodecontraseñas2'

Revision ID: 592b0fadf74e
Revises: 1ad0dacf223b
Create Date: 2025-07-18 13:14:15.198204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592b0fadf74e'
down_revision: Union[str, None] = '1ad0dacf223b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contraseña', table_name='turista')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('contraseña', 'turista', ['contraseña'], unique=True)
    # ### end Alembic commands ###
