"""'Actualizacion2'

Revision ID: 5e9e064e2e66
Revises: 33f5b6a551f7
Create Date: 2025-07-13 13:46:46.094558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9e064e2e66'
down_revision: Union[str, None] = '33f5b6a551f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informe', sa.Column('nombre', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informe', 'nombre')
    # ### end Alembic commands ###
