"""'CampoActuAdm2'

Revision ID: 912f02bcb7df
Revises: a4a20cb29d8a
Create Date: 2025-07-30 20:11:52.221085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '912f02bcb7df'
down_revision: Union[str, None] = 'a4a20cb29d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrador', 'contrasena',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrador', 'contrasena',
               existing_type=sa.VARCHAR(length=100),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
