"""cambios4

Revision ID: a0c0bb44cf2f
Revises: c3644af48091
Create Date: 2025-07-12 16:41:32.094001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c0bb44cf2f'
down_revision: Union[str, None] = 'c3644af48091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacion', sa.Column('fecha_envio', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notificacion', 'fecha_envio')
    # ### end Alembic commands ###
