"""'CampoActuAdm'

Revision ID: a4a20cb29d8a
Revises: 0e8c526c8322
Create Date: 2025-07-30 19:59:14.364278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4a20cb29d8a'
down_revision: Union[str, None] = '0e8c526c8322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('contrasena', sa.VARCHAR(length=15), nullable=True))
    op.drop_index('contraseña', table_name='administrador')
    op.create_unique_constraint(None, 'administrador', ['contrasena'])
    op.drop_column('administrador', 'contraseña')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('contraseña', mysql.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'administrador', type_='unique')
    op.create_index('contraseña', 'administrador', ['contraseña'], unique=True)
    op.drop_column('administrador', 'contrasena')
    # ### end Alembic commands ###
