"""Agregar campos recuperación contraseña

Revision ID: b50442311d11
Revises: 912f02bcb7df
Create Date: 2025-08-22 16:44:38.702260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50442311d11'
down_revision: Union[str, None] = '912f02bcb7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('pin_recuperacion', sa.String(length=6), nullable=True))
    op.add_column('turista', sa.Column('expira_pin', sa.DateTime(), nullable=True))
    op.add_column('turista', sa.Column('token_recuperacion', sa.String(length=255), nullable=True))
    op.add_column('turista', sa.Column('expira_token', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turista', 'expira_token')
    op.drop_column('turista', 'token_recuperacion')
    op.drop_column('turista', 'expira_pin')
    op.drop_column('turista', 'pin_recuperacion')
    # ### end Alembic commands ###
