"""'Agregamos_Campo_faltante'

Revision ID: bfe75fcc8088
Revises: ca9052441bd7
Create Date: 2025-08-24 23:24:24.220152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfe75fcc8088'
down_revision: Union[str, None] = 'ca9052441bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('tipo_identificacion', sa.String(length=5), nullable=True))
    op.alter_column('turista', 'identificacion',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turista', 'identificacion',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('turista', 'tipo_identificacion')
    # ### end Alembic commands ###
