"""'Add_ralation_the_table_Ubicacion_with_table_Ciudad'

Revision ID: ca9052441bd7
Revises: f85df5016f98
Create Date: 2025-08-24 21:40:12.396801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9052441bd7'
down_revision: Union[str, None] = 'f85df5016f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ubicacion', sa.Column('ciudad_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'ubicacion', ['ciudad_id'])
    op.create_foreign_key(None, 'ubicacion', 'ciudad', ['ciudad_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ubicacion', type_='foreignkey')
    op.drop_constraint(None, 'ubicacion', type_='unique')
    op.drop_column('ubicacion', 'ciudad_id')
    # ### end Alembic commands ###
