"""'Actualizacion3'

Revision ID: da74fe659509
Revises: 5e9e064e2e66
Create Date: 2025-07-13 14:01:41.696197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da74fe659509'
down_revision: Union[str, None] = '5e9e064e2e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrador', 'celular',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('administrador', 'identificacion',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrador', 'identificacion',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('administrador', 'celular',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
