"""'Cifradodecontraseñas3'

Revision ID: e86d465cd4be
Revises: 592b0fadf74e
Create Date: 2025-07-18 13:35:00.092080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e86d465cd4be'
down_revision: Union[str, None] = '592b0fadf74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turista', 'contraseña',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turista', 'contraseña',
               existing_type=sa.VARCHAR(length=100),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
