"""'Add_table_ciudad_add_ralation_with_table_Turista'

Revision ID: f85df5016f98
Revises: b50442311d11
Create Date: 2025-08-24 20:47:55.339292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f85df5016f98'
down_revision: Union[str, None] = 'b50442311d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.add_column('turista', sa.Column('ciudad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turista', 'ciudad', ['ciudad_id'], ['id'])
    op.drop_column('turista', 'ciudad_residencia')
    op.drop_column('ubicacion', 'ciudad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ubicacion', sa.Column('ciudad', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('turista', sa.Column('ciudad_residencia', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'turista', type_='foreignkey')
    op.drop_column('turista', 'ciudad_id')
    op.drop_table('ciudad')
    # ### end Alembic commands ###
