"""'CampoTurista'

Revision ID: 030e95947b54
Revises: c00ad54f72d1
Create Date: 2025-10-24 07:05:23.551286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030e95947b54'
down_revision: Union[str, None] = 'c00ad54f72d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turista', 'fecha_registro')
    # ### end Alembic commands ###
