"""crear tabla persona_reserva

Revision ID: 095aafc12f8a
Revises: 5c812c1edd5b
Create Date: 2025-11-01 23:31:07.882830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095aafc12f8a'
down_revision: Union[str, None] = '5c812c1edd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=False),
    sa.Column('identificacion', sa.String(length=15), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_reserva_id'), 'persona_reserva', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_reserva_id'), table_name='persona_reserva')
    op.drop_table('persona_reserva')
    # ### end Alembic commands ###
