"""crea tabla persona_reserva

Revision ID: 0f317504225f
Revises: b83a99b603df
Create Date: 2025-11-01 23:09:48.893577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f317504225f'
down_revision: Union[str, None] = 'b83a99b603df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserva', 'costo_final',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_reserva_id'), 'reserva', ['id'], unique=False)
    op.drop_constraint('reserva_ibfk_1', 'reserva', type_='foreignkey')
    op.drop_column('reserva', 'id_informe')
    op.drop_column('reserva', 'comprobante_pdf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('comprobante_pdf', sa.BLOB(), nullable=True))
    op.add_column('reserva', sa.Column('id_informe', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('reserva_ibfk_1', 'reserva', 'informe', ['id_informe'], ['id'])
    op.drop_index(op.f('ix_reserva_id'), table_name='reserva')
    op.alter_column('reserva', 'costo_final',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
