"""'nuevoCampoPlanes'

Revision ID: 1b6a4fe18170
Revises: 030e95947b54
Create Date: 2025-10-30 18:51:25.165117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6a4fe18170'
down_revision: Union[str, None] = '030e95947b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('mostrar_en_carrusel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'mostrar_en_carrusel')
    # ### end Alembic commands ###
