"""ajustes tabla persona_reserva

Revision ID: 307a831b7456
Revises: 095aafc12f8a
Create Date: 2025-11-04 15:51:12.725210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '307a831b7456'
down_revision: Union[str, None] = '095aafc12f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona_reserva', sa.Column('edad', sa.Integer(), nullable=False))
    op.add_column('reserva', sa.Column('comprobante_pdf', sa.LargeBinary(), nullable=True))
    op.add_column('reserva', sa.Column('id_informe', sa.Integer(), nullable=True))
    op.alter_column('reserva', 'costo_final',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('ix_reserva_id', table_name='reserva')
    op.create_foreign_key(None, 'reserva', 'informe', ['id_informe'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserva', type_='foreignkey')
    op.create_index('ix_reserva_id', 'reserva', ['id'], unique=False)
    op.alter_column('reserva', 'costo_final',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('reserva', 'id_informe')
    op.drop_column('reserva', 'comprobante_pdf')
    op.drop_column('persona_reserva', 'edad')
    # ### end Alembic commands ###
