"""'Nuevos_campos_en_tble_turista'

Revision ID: 384f88a0b900
Revises: f162ae6f4502
Create Date: 2025-09-08 17:52:54.869515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '384f88a0b900'
down_revision: Union[str, None] = 'f162ae6f4502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('contrasena', table_name='administrador')
    op.alter_column('favorito', 'id_turista',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('favorito', 'id_plan',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'plan', ['descripcion_corta'])
    op.add_column('turista', sa.Column('intentos_fallidos', sa.Integer(), nullable=True))
    op.add_column('turista', sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turista', 'bloqueado_hasta')
    op.drop_column('turista', 'intentos_fallidos')
    op.drop_constraint(None, 'plan', type_='unique')
    op.alter_column('favorito', 'id_plan',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('favorito', 'id_turista',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index('contrasena', 'administrador', ['contrasena'], unique=True)
    # ### end Alembic commands ###
