"""'NuevaTablaTargeta'

Revision ID: 4cbb5d42aa86
Revises: 1e6480296224
Create Date: 2025-11-04 23:01:15.566467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbb5d42aa86'
down_revision: Union[str, None] = '1e6480296224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_tarjeta', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=16), nullable=False),
    sa.Column('fecha_vencimiento', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('turista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turista_id'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarjeta')
    # ### end Alembic commands ###
