"""'nuevos_campos_Tabla_Admin'

Revision ID: 4dc588629c3f
Revises: 384f88a0b900
Create Date: 2025-09-10 06:52:24.863567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc588629c3f'
down_revision: Union[str, None] = '384f88a0b900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('intentos_fallidos', sa.Integer(), nullable=True))
    op.add_column('administrador', sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrador', 'bloqueado_hasta')
    op.drop_column('administrador', 'intentos_fallidos')
    # ### end Alembic commands ###
