"""'CampoTerminosTablaTurista'

Revision ID: 6a16bb3828b3
Revises: deef0a8d314f
Create Date: 2025-09-16 00:40:00.897182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a16bb3828b3'
down_revision: Union[str, None] = 'deef0a8d314f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('acepto_terminos', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turista', 'acepto_terminos')
    # ### end Alembic commands ###
