"""'nuevoCampoInformes'

Revision ID: 96c3ca93f8f7
Revises: 1b6a4fe18170
Create Date: 2025-11-01 17:58:10.960348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c3ca93f8f7'
down_revision: Union[str, None] = '1b6a4fe18170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informe', sa.Column('ruta_pdf', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informe', 'ruta_pdf')
    # ### end Alembic commands ###
