"""'Relacion_turista_reservas'

Revision ID: 9be64440a234
Revises: 4dc588629c3f
Create Date: 2025-09-14 11:33:51.350836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be64440a234'
down_revision: Union[str, None] = '4dc588629c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('id_turista', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reserva', 'turista', ['id_turista'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserva', type_='foreignkey')
    op.drop_column('reserva', 'id_turista')
    # ### end Alembic commands ###
