"""'NuevoCampo'

Revision ID: b7c5606ecb2f
Revises: 6a16bb3828b3
Create Date: 2025-09-23 00:34:52.342311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c5606ecb2f'
down_revision: Union[str, None] = '6a16bb3828b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('comprobante_pdf', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'comprobante_pdf')
    # ### end Alembic commands ###
