"""'AgregamosCampoturista'

Revision ID: c00ad54f72d1
Revises: 1b318a9ae957
Create Date: 2025-10-23 18:54:46.860409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00ad54f72d1'
down_revision: Union[str, None] = '1b318a9ae957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turista', sa.Column('estado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turista', 'estado')
    # ### end Alembic commands ###
