"""'EspacioEnCamposDeLatablaPlanes'

Revision ID: deef0a8d314f
Revises: d46224fa348e
Create Date: 2025-09-15 20:28:53.665616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'deef0a8d314f'
down_revision: Union[str, None] = 'd46224fa348e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'descripcion',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('plan', 'descripcion_corta',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'descripcion_corta',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('plan', 'descripcion',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
