"""'BaseDeDatos'

Revision ID: e73c59afaa7c
Revises: 
Create Date: 2025-09-14 13:22:36.273726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73c59afaa7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=True),
    sa.Column('identificacion', sa.String(length=15), nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=100), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('auditoria_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administrador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_plan_id'), 'auditoria_plan', ['id'], unique=False)
    op.create_table('informe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('turista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=True),
    sa.Column('identificacion', sa.String(length=30), nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=100), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('pin_recuperacion', sa.String(length=6), nullable=True),
    sa.Column('expira_pin', sa.DateTime(), nullable=True),
    sa.Column('token_recuperacion', sa.String(length=255), nullable=True),
    sa.Column('expira_token', sa.DateTime(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=40), nullable=True),
    sa.Column('costo_persona', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.Column('id_informe', sa.Integer(), nullable=True),
    sa.Column('id_Admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Admin'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['id_informe'], ['informe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('descripcion_corta'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_turista', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.Date(), nullable=True),
    sa.Column('costo_final', sa.Integer(), nullable=True),
    sa.Column('disponibilidad', sa.Boolean(), nullable=True),
    sa.Column('numero_personas', sa.Integer(), nullable=True),
    sa.Column('id_informe', sa.Integer(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_informe'], ['informe.id'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitud', sa.VARCHAR(length=30), nullable=True),
    sa.Column('latitud', sa.VARCHAR(length=30), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion')
    op.drop_table('reserva')
    op.drop_table('favorito')
    op.drop_table('plan')
    op.drop_table('turista')
    op.drop_table('informe')
    op.drop_index(op.f('ix_auditoria_plan_id'), table_name='auditoria_plan')
    op.drop_table('auditoria_plan')
    op.drop_table('ciudad')
    op.drop_table('administrador')
    # ### end Alembic commands ###
